name: pr-check

on:
  pull_request:

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci

      - name: Check lint and format
        run: npm run lint-ci