name: publish-on-tag

on:
  push:
    tags:
      - '**'

permissions:
  write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Prepare publish
        run: npm run prepublishOnly
      - name: Publish
        run: npm publish
